--- BETWEEN OPERATOR: MATCH VALUES AGAINST A RANGE OF VALUES ---
SELECT * FROM payment
WHERE amount
BETWEEN 7 AND 8;
--
SELECT COUNT (amount) FROM payment
WHERE amount
BETWEEN 7 AND 8;
--
SELECT * FROM payment
WHERE payment_date
BETWEEN '2007-02-01' AND '2007-02-15';

--- IN OPERATOR: CREATE A CONDITION THAT CHECKS TO SEE IF A VALUE IS INCLUDED IN A LIST OF MULTIPLE
SELECT * FROM payment
WHERE amount IN (0.99, 1.99, 2.99);
--
-- NOT IN: EXCEPT THE GIVEN CONDITION 
SELECT first_name, last_name, email
FROM customer
WHERE first_name NOT IN ('John', 'Mark', 'Julie');

--- LIKE|ILIKE OPERATOR: ALLOWS US TO PERFORM PATTERN MATCHING
-- %: CAN HAVE MULTIPLE CHRACTER | _: HAS SINGLE CHARACTER
-- LIKE: CASE SENSITIVE | ILIKE: CASE INSENSITIVE
SELECT * FROM customer
WHERE first_name LIKE 'J%';
--
SELECT * FROM customer
WHERE first_name LIKE 'B____a';
-- count
SELECT COUNT (*) FROM customer
WHERE first_name LIKE 'J%';
-- combined conditions
SELECT * FROM customer
WHERE first_name LIKE 'J%' AND last_name LIKE 'S%';
-- NOT LIKE
SELECT * FROM customer
WHERE first_name LIKE 'A%' AND last_name NOT LIKE 'A%';

--- AGGREGATION FUNCTIONS: TAKES MULTIPLE IMPUTS AND RETURNS A SINGLE OUTPUT
-- MOST COMMON AGGREGATE FUNCTIONS: AVG(): FOR AVERAGE| MIN(): MINIMUM VALUE| MAX(): MAXIMUM VALUE| SUM(): SUM OF ALL VALUES| ROUND(): ROUNDS OFF DECIMAL
SELECT ROUND(AVG(replacement_cost),2), MIN(replacement_cost), MAX(replacement_cost), SUM(replacement_cost)   
FROM film; 

--- AS STATEMENT: AS CLAUSE ALLOWS US TO CREATE ALIAS FROM A COLUMN OR RESULT
SELECT rating
AS reviews
FROM film;